language: python
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.6"
install:
  - pip install flake8
script:
  # lint the code changes generating an error if warning introduced
  - git diff -U0 $TRAVIS_COMMIT_RANGE | flake8 --diff
  # print the other warnings but don't report it as an error
  - flake8 --exit-zero
