name: addie
channels:
- conda-forge
- marshallmcdonnell
- mantid
dependencies:
- python=3.6
- configparser
- mantid-total-scattering-python-wrapper
- mantid-workbench
- periodictable
- psutil
- setuptools
- simplejson
